### ISSUE TITLE
Tupl version incompatibility

### ISSUE THREAD

**Issue by broneill** [jekyllislandtours/conceptual-tupl#4]
I noticed that conceptual-tupl depends on the Scanner and EntryConsumer interfaces. Be advised that in the next major version of Tupl, the EntryConsumer interface is gone and the Scanner interface has been repurposed. I recommend switching over to using the Cursor interface directly, which isn't changing.

**Comment by broneill** [comment]
Also, if you want to count index entries as efficiently as possible, call the count method. It's not transactional, and so if you want a transactional count use a Cursor with autoload disabled. This avoids the overhead of copying the values into short-lived objects that you're just discarding.

**Comment by xfthhxk** [comment]
Thanks @broneill.  I'll make the changes.
